#!/bin/bash

CHECK="\xE2\x9C\x94"
X="\xE2\x9D\x8c"

printf "\n\n"
printf "#  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #\n"
printf "#  ~~~~~~                      ~~~~~~~ #\n"
printf "#  ~~~~   PGP Signature Checker   ~~~~ #\n"
printf "#  ~~~~~~                      ~~~~~~~ #\n"
printf "#  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #\n"
printf "\n\n\n\n"

tput sgr0


printf "~~~~~~~ Drag file to verify here ~~~~~~~\n\n"

read -d ' ' file

printf "\n\n\n\n\n"
printf "~~~~~~~ Drag signature file here ~~~~~~~\n\n"

read -d ' ' sig

printf "\n\n"

check_sig() {
  tput sgr0
  gpg --verify $sig $file > /tmp/sigresults 2>&1

  STATUS=$?
  if [ $STATUS -eq 0 ]; then
    #cat /tmp/sigresults
    tput setaf 2
    printf "\n\n\e[32;1m          Signature is valid $CHECK \n\n\n\n"
  elif [ $STATUS -eq 1 ]; then
    #cat /tmp/sigresults
    tput setaf 1
    printf "\n\n\e[32;1m          Invalid signature $X \n\n\n\n"
  elif [ $STATUS -eq 2 ]; then
    key=$(cat /tmp/sigresults | grep RSA | rev | cut -d " " -f1 | rev)
    if [ -z "$key" ]; then
      tput setaf 1
      printf "Unknown error - make sure you're uploading the right files\n\n\n\n"
      tput sgr0
      exit 1
    fi
    printf "Receiving key $key...\n\n"
    gpg --recv-key $key > /tmp/downloadresults
    check_sig
  fi
}

check_sig
tput sgr0
read -p "Press enter for full details"

cat /tmp/sigresults